---
version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: phoenix_hello_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
